#!/usr/bin/bash

export PATH=~/.npm-global/bin:$PATH

Bootstrap(){

    echo -e "\n\tInstalling templates"
    mkdir -p ~/.local/share/pandoc/templates
    cp $PWD/templates/* ~/.local/share/pandoc/templates

    echo -e "\n\tInstalling tectonic"
    sudo xbps-install tectonic || { echo -e "\n\tfailed to install tectonic" \
    && return 1; }

    echo -e "\n\tInstalling npm as build dependency for pandoc-url2cite"
    sudo xbps-install nodejs \
    || { echo -e "\n \tfailed to install pandoc-url2cite" \
    && return 1; }

    echo -e "\n\tInstalling librsvg-utils for mermaid-filter"
    sudo xbps-install librsvg-utils \
    || { echo -e "\n \tfailed to install librsvg-utils" \
    && return 1; }

    echo -e "\n\tInstalling pandoc-url2cite"
    sudo npm install -g pandoc-url2cite \
    || { echo -e "\n \tfailed to install pandoc-url2cite" \
    && return 1; }

    echo -e "\n\tInstalling mermaid-filter"
    sudo npm install -g mermaid-filter \
    || { echo -e "\n \tfailed to install mermaid-filter" \
    && return 1; }

    echo -e "\n\tInstalling tectonic"
    sudo xbps-install tectonic \
    || { echo -e "\n \tfailed to install tectonic" \
    && return 1; }

return 0
}

Help(){
    echo -e "\n\tThis tool allows you to easily compile markdown documents into pdf text\
    \n\n\tUsage: [file] -option(s) \
    \n\tIf only a file is specified the default CSL and template will be used \
    \n\n\tOptions: \n\t-h: print this help and exit \
    \n\t-c: path to csl file \
    \n\t-t: path to latex template \
    \n\t-nf: do not apply citation filters \
    \n\t-no: do not open the pdf after conversion \
    \n\t-b: bootstrap this helper \
    \n\t-m: enable mermaid figures"
}

# Function looks dumb, but CanLII will sometimes respond with a 'v.'
# between parties and sometimes the standard 'v' this fixes that.
Getshortname(){
while read soc ; do
	pstring1=${soc% *v* *}
	pstring2=${soc#* *v* }
	party1=$(sed 's/Corp.\|ltd.\|Co.\|The//' <<< "$pstring1")
	party2=$(sed 's/Corp.\|ltd.\|Co.\|The//' <<< "$pstring2")
	style="$party1 v $party2"
	length=$(wc -w <<< "style")
	if [ "$length" -lt 4 ] ; then
	 echo "$party1 v $party2"
	else
	 if [ "$party1" == "R" ] ; then
	 	echo "${party2%% *}"
	 else
	 	echo "${party1%% *}"
	 fi
	fi
done
}

Getcitation(){
shortname=""
url=${link#*canlii.org}
key=""
db=$(cut -d '/' -f4 <<< $url )
jur=$(cut -d '/' -f3 <<< $url )
ident=$(cut -d '/' -f7<<< $url )
shortname=""
dbid=$(awk '$0~i{print $2}' i="$db " $HOME/.local/share/methodius/equ/master)

cacheresponse=$(grep -m1 "$url" $HOME/.local/share/methodius/canliicache | cut -d '|' -f2)
if [ -n "${cacheresponse}" ] ; then
	citation="$cacheresponse"
	SHORTNAMES[$link]=$(grep -m1 "$url" $HOME/.local/share/methodius/canliicache | cut -d '|' -f3)
	return 0
else

requesturl="https://api.canlii.org/v1/caseBrowse/en/$dbid/$ident/?api_key=$key"
response=$(wget -qO- "$requesturl")
if [ -z "${response}" ] ; then
	echo "failed to connect to canlii with url $requesturl, exiting"
	exit 1
fi

soc=$(awk -F '"' '/title":/ {print $4}' <<< "$response")
citekeyresponse=$(awk -F '"' '/citation":/ {print $4}' <<< "$response")
citekey=${citekeyresponse%\ \(CanLII)*}
shortname=$(Getshortname <<< "$soc")
SHORTNAMES[$link]="$shortname"

if [ -n "${soc}" ] && [ -n "${citekey}" ] ; then
	citation="*$soc,* $citekey"
	echo "$citation"
	echo "$url|$citation|$shortname" >> $HOME/.local/share/methodius/canliicache
else
	echo -e "failed to find database for canlii response\nresponse:\t$response\ndb:\t$db\ndbid:\t$dbib\njurisdiction:$jur\nidentity:\t$ident"
	exit 1
fi
fi
}

Findlinks(){
	count=0
	declare -A CITATIONS
	declare -A NOTENUMBER
	declare -A PINPOINTS
	declare -A LASTCITE
	declare -A SHORTNAMES
	while read line ; do
	case $line in
	*canlii*)
	chunk=""
	link=""
	pinpoint=""
	distance=""
	suffix=""
	pincite=""
	count=$(( $count + 1 ))
		chunk="${line:1:${#line}-2}"
		pinpoint=$(awk '$1=""; {print $0}' <<< "$chunk")
		link=$(awk '{print $1}' <<< "$chunk")
		if [ -z "${CITATIONS["$link"]}" ] ; then
		 Getcitation
		 if ! grep -q "$chunk" /tmp/methodius/uniq_test ; then
		  suffix=" \[${SHORTNAMES[$link]}\]"
		 fi
		 CITATIONS["$link"]="$citation"
		 NOTENUMBER["$link"]="$count"
		 sed -i "0,\|$chunk|{s|$line|\^\[$citation$pinpoint$suffix\]|}" $copy
		else
		 distance=$(($count-${NOTENUMBER[$link]}))
		 distancelast=$(($count - ${LASTCITE[$link]}))
		 if [ ! "${PINPOINTS[$link]}" == "$pinpoint" ] ; then
		  pincite="$pinpoint"
		 fi
		 if [ "$distance" -eq 1 ] ; then
		  sed -i "0,\|$chunk|{s|$line|\^\[*ibid*$pincite\]|}" $copy
		 elif [ "$distancelast" -eq 1 ] ; then
		  sed -i "0,\|$chunk|{s|$line|\^\[*ibid*$pincite\]|}" $copy
		 else
			 sed -i "0,\|$chunk|{s|$line|\^\[*${SHORTNAMES[$link]}, supra* note ${NOTENUMBER[$link]},$pincite\]|}" $copy
		 fi
		fi
		LASTCITE[$link]="$count"
		PINPOINTS[$link]="$pinpoint"
	;;
	*)
		count=$(( $count + 1 ))
	;;
	esac

done < <(grep -o '(.*\.canlii.org.*\.html.*)\|\^\[.*\]')

	echo "Got Shortames ${SHORTNAMES[@]}"
}

Legalcite(){
output="$PWD/${base%%.*}.pdf"
CSL="$HOME/.local/share/pandoc/templates/mcgill-en.csl"
filename=$(basename "$file")
mkdir -p /tmp/methodius/
copy="/tmp/methodius/$base"
cp "$file" /tmp/methodius/

echo "copy is $copy"
awk 'match($0, /\(.*\.canlii.org.*\.html/) {gsub(")",""); print substr($0, RSTART+1, RLENGTH)}' $copy | uniq -u > /tmp/methodius/uniq_test
Findlinks < "$copy"
input="$copy"
}

SetTemplate(){
    if [[ -z $template ]] ; then
        template="methodius"
    fi
    if [[ -z $CSL ]] ; then
        CSL="$HOME/.local/share/pandoc/templates/chicago_note.csl"
    fi
    if [[ $nofilters ]] ; then
    filters=""
    else
    filters="--filter=pandoc-url2cite --citeproc"
    fi
    if [[ -v $open_after ]] ; then
    open_after=true
    fi
    if [[ -v $devour ]] ; then
    devour=true
    fi
    if $legal ; then
	Legalcite
    fi
    if [[ -z $input ]] ; then
	    input="$file"
    fi

}

Convertpdf(){
    pandoc \
    $filters \
    $mermaid \
    --csl $CSL \
    --pdf-engine=tectonic \
    --template $template \
    -s $input \
    -o $output \
    && return 0 || return 1
}

Post_open() {
    if $open_after ; then
        if $devour ; then
            devour zathura $output || exo-open $output
        else
            zathura $output || exo-open $output
        fi
    fi
}

Cleanmermaid(){
if $cleanMermaid ; then
    rm mermaid-filter.err
    rm -rf mermaid-images/
fi
}

POSITIONAL=()
while [[ $# -gt 0 ]]
do
key="$1"

case $key in
    -b|--bootstrap)
    EXTENSION="$2"
    Bootstrap && exit 0 || exit 1
    ;;
    -t|--template)
    template="$2"
    shift
    shift
    ;;
    -c|--csl)
    CSL="$2"
    shift 
    shift
    ;;
    -h|--help)
    Help && exit 0
    ;;
    -nf|--filters)
    nofilters=true
    shift
    ;;
    -no|--no-open)
    open_after=false
    shift
    ;;
    -nd|--no-devour)
    devour=false
    shift
    ;;
    -m|--mermaid)
    mermaid="--filter=mermaid-filter"
    mkdir mermaid-images
    cleanMermaid=true
    shift
    ;;
    -l|--legal)
    legal=true
    shift
    ;;
    *)
    POSITIONAL+=("$1")
    shift
    ;;
esac
done
set -- "${POSITIONAL[@]}" # restore positional parameters

file=$1
base=$(basename $1)
output="${base%%.*}.pdf"

SetTemplate
echo -e "\t[INPUT VARIABLES]\n\tinput: $input \n\ttemplate: $template \n\tCSL: $CSL \n\toutput: $output\n"
Convertpdf && Cleanmermaid && Post_open
